const GET_ALL_THEMES_REQUEST = 'GET_ALL_THEMES_REQUEST';
const GET_ALL_THEMES_SUCCESS = 'GET_ALL_THEMES_SUCCESS';
const GET_ALL_THEMES_FAILURE = 'GET_ALL_THEMES_FAILURE';
const SET_ACTIVE_THEME_REQUEST = 'SET_ACTIVE_THEME_REQUEST';
const SET_ACTIVE_THEME_SUCCESS = 'SET_ACTIVE_THEME_SUCCESS';
const SET_ACTIVE_THEME_FAILURE  = 'SET_ACTIVE_THEME_FAILURE';

export {
	GET_ALL_THEMES_REQUEST,
	GET_ALL_THEMES_SUCCESS,
	GET_ALL_THEMES_FAILURE,
	SET_ACTIVE_THEME_REQUEST,
	SET_ACTIVE_THEME_SUCCESS,
	SET_ACTIVE_THEME_FAILURE,
};