const GET_ALL_LAYOUTS_REQUEST = 'GET_ALL_LAYOUTS_REQUEST';
const GET_ALL_LAYOUTS_SUCCESS = 'GET_ALL_LAYOUTS_SUCCESS';
const GET_ALL_LAYOUTS_FAILURE = 'GET_ALL_LAYOUTS_FAILURE';
const SET_ACTIVE_LAYOUT_REQUEST = 'SET_ACTIVE_LAYOUT_REQUEST';
const SET_ACTIVE_LAYOUT_SUCCESS = 'SET_ACTIVE_LAYOUT_SUCCESS';
const SET_ACTIVE_LAYOUT_FAILURE = 'SET_ACTIVE_LAYOUT_FAILURE';

export {
	GET_ALL_LAYOUTS_REQUEST,
	GET_ALL_LAYOUTS_SUCCESS,
	GET_ALL_LAYOUTS_FAILURE,
	SET_ACTIVE_LAYOUT_REQUEST,
	SET_ACTIVE_LAYOUT_SUCCESS,
	SET_ACTIVE_LAYOUT_FAILURE,
};