const TOGGLE_NAV_DISPLAY = 'TOGGLE_NAV_DISPLAY';
const CLOSE_NAV_DISPLAY = 'CLOSE_NAV_DISPLAY';
const GET_NAV_DISPLAY_SIZE = 'GET_NAV_DISPLAY_SIZE';
const SET_NAV_DISPLAY_SIZE = 'SET_NAV_DISPLAY_SIZE';

export {
	TOGGLE_NAV_DISPLAY,
	CLOSE_NAV_DISPLAY,
	GET_NAV_DISPLAY_SIZE,
	SET_NAV_DISPLAY_SIZE,
};
